# OrangeFox-specific flags for ruby

# Screen
OF_SCREEN_H := 2400
OF_SCREEN_W := 1080
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48

# Navigation
OF_ALLOW_DISABLE_NAVBAR := 0
OF_CLOCK_POS := 1

# Features
OF_FL_KEY_COMBO := 0
OF_FLASHLIGHT_ENABLE := 1
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1

# OTA and patching
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_PATCH_AVB20 := 1

# HyperOS specific
OF_DEFAULT_KEYMASTER_VERSION := 4.1
OF_VANILLA_BUILD := 0

# Maintainer
OF_MAINTAINER := Arush
