#!/bin/bash

# Device identifiers
export FOX_BUILD_DEVICE="ruby"
export FOX_AB_DEVICE=1
export FOX_VIRTUAL_AB_DEVICE=1

# Maintainer info
export FOX_BUILD_USER="Arush"
export FOX_MAINTAINER="Arush"
export FOX_MAINTAINER_PATCH_VERSION="1"

# AVB and HyperOS
export OF_PATCH_AVB20=1
export OF_DEFAULT_KEYMASTER_VERSION=4.1

# Build flags
export ALLOW_MISSING_DEPENDENCIES=true
export OF_USE_MAGISKBOOT=1
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
